app = "hotosm-staging"

kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "make release"
  strategy = "rolling"

[env]
  PORT = "80"
  BASE_URL = "https://hotosm-staging.fly.dev"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    method = "get"
    path = "/"
    protocol = "https"
    tls_skip_verify = true
    grace_period = "60s"
    interval = 30000
    timeout = 3000
    restart_limit = 6

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
