# Generated by Django 4.1 on 2022-08-16 16:35

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0076_modellogentry_revision"),
        ("app", "0002_homepage_magazinearticlepage_magazineindexpage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="layout",
            field=wagtail.fields.StreamField(
                [
                    (
                        "summary_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(form_classname="full"),
                                )
                            ]
                        ),
                    ),
                    ("richtext", wagtail.blocks.RichTextBlock()),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.CreateModel(
            name="SiteBannerSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_active", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=300)),
                ("description", wagtail.fields.RichTextField()),
                ("url", models.CharField(max_length=800)),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
