# Generated by Django 4.1 on 2022-08-17 10:29

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_magazinearticlepage_layout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazinearticlepage",
            name="layout",
            field=wagtail.fields.StreamField(
                [
                    ("richtext", wagtail.blocks.RichTextBlock()),
                    (
                        "embeddable_code",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="(Internal use only.) Explain what this does for other editors. Not displayed on the website.",
                                        required=False,
                                    ),
                                ),
                                ("html", wagtail.blocks.CharBlock(max_length=10000)),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="layout",
            field=wagtail.fields.StreamField(
                [
                    ("richtext", wagtail.blocks.RichTextBlock()),
                    (
                        "embeddable_code",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="(Internal use only.) Explain what this does for other editors. Not displayed on the website.",
                                        required=False,
                                    ),
                                ),
                                ("html", wagtail.blocks.CharBlock(max_length=10000)),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
