# Generated by Django 4.1 on 2022-08-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_magazinearticlepage_layout_alter_staticpage_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="show_footer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="show_header",
            field=models.BooleanField(default=True),
        ),
    ]
