# Generated by Django 4.1 on 2022-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_magazinearticlepage_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="short_description",
            field=models.CharField(default=" ", max_length=300),
            preserve_default=False,
        ),
    ]
