# Generated by Django 4.1 on 2022-09-06 15:50

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_topicpage_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="page_contact_contact_email",
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="page_contact_link_label",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="page_contact_title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="short_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="topichomepage",
            name="layout",
            field=wagtail.fields.StreamField(
                [
                    (
                        "links_gallery",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=250)),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "label",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Will override the page title if specified",
                                                        max_length=250,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.blocks.URLBlock(
                                                        help_text="Will override the page URL if specified",
                                                        max_length=1000,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=250, required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "more_info",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "label",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Will override the page title if specified",
                                                    max_length=250,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    help_text="Will override the page URL if specified",
                                                    max_length=1000,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "description",
                                                wagtail.blocks.CharBlock(
                                                    max_length=250, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "featured_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Will override the page title if specified",
                                        max_length=250,
                                    ),
                                ),
                                ("description", wagtail.blocks.RichTextBlock()),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "link_page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "link_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Will override the page title if specified",
                                        max_length=250,
                                        required=False,
                                    ),
                                ),
                                (
                                    "link_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Will override the page URL if specified",
                                        max_length=1000,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("richtext", wagtail.blocks.RichTextBlock()),
                    (
                        "simple_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Will override the page title if specified",
                                        max_length=250,
                                        required=False,
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Will override the page URL if specified",
                                        max_length=1000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(
                                        max_length=250, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="layout",
            field=wagtail.fields.StreamField(
                [
                    (
                        "links_gallery",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=250)),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "label",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Will override the page title if specified",
                                                        max_length=250,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.blocks.URLBlock(
                                                        help_text="Will override the page URL if specified",
                                                        max_length=1000,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=250, required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                                (
                                    "more_info",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "label",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Will override the page title if specified",
                                                    max_length=250,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    help_text="Will override the page URL if specified",
                                                    max_length=1000,
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "description",
                                                wagtail.blocks.CharBlock(
                                                    max_length=250, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "featured_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Will override the page title if specified",
                                        max_length=250,
                                    ),
                                ),
                                ("description", wagtail.blocks.RichTextBlock()),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "link_page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "link_label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Will override the page title if specified",
                                        max_length=250,
                                        required=False,
                                    ),
                                ),
                                (
                                    "link_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Will override the page URL if specified",
                                        max_length=1000,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("richtext", wagtail.blocks.RichTextBlock()),
                    (
                        "simple_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "label",
                                    wagtail.blocks.CharBlock(
                                        help_text="Will override the page title if specified",
                                        max_length=250,
                                        required=False,
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Will override the page URL if specified",
                                        max_length=1000,
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(
                                        max_length=250, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
