# Generated by Django 4.1.1 on 2022-09-29 13:37

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_taggedevent_content_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaggedTopic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_tags",
                        to="app.topicpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="hotosmtag",
            options={},
        ),
        migrations.RemoveField(
            model_name="organisationpage",
            name="category",
        ),
        migrations.AddField(
            model_name="organisationpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="app.TaggedOrganisation",
                to="app.HOTOSMTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="taggedorganisation",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_organisations",
                to="app.hotosmtag",
            ),
        ),
        migrations.DeleteModel(
            name="OrganisationType",
        ),
        migrations.AddField(
            model_name="taggedtopic",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_tags",
                to="app.hotosmtag",
            ),
        ),
        migrations.AddField(
            model_name="topicpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="app.TaggedTopic",
                to="app.HOTOSMTag",
                verbose_name="Tags",
            ),
        ),
    ]
