# Generated by Django 4.1.1 on 2022-09-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_activationindexpage_short_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationindexpage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="activationprojectpage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="directorypage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="magazineindexpage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="magazinesection",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="opportunitypage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="organisationpage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="personpage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="topichomepage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="short_summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
