# Generated by Django 4.1.1 on 2022-09-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_activationindexpage_short_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationindexpage",
            name="frontmatter",
            field=models.JSONField(
                blank=True, help_text="Metadata from the legacy site", null=True
            ),
        ),
        migrations.AddField(
            model_name="directorypage",
            name="frontmatter",
            field=models.JSONField(
                blank=True, help_text="Metadata from the legacy site", null=True
            ),
        ),
        migrations.AddField(
            model_name="magazineindexpage",
            name="frontmatter",
            field=models.JSONField(
                blank=True, help_text="Metadata from the legacy site", null=True
            ),
        ),
        migrations.AddField(
            model_name="magazinesection",
            name="frontmatter",
            field=models.JSONField(
                blank=True, help_text="Metadata from the legacy site", null=True
            ),
        ),
    ]
