# Generated by Django 4.1.1 on 2022-10-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_countrypage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrypage",
            name="isoa3",
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
