# Generated by Django 4.1.1 on 2022-10-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_countrypage_isoa3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Describe this image as literally as possible. If you can close your eyes, have someone read the alt text to you, and imagine a reasonably accurate version of the image, you're on the right track. More info: https://axesslab.com/alt-texts/",
                max_length=1024,
                null=True,
            ),
        ),
    ]
