# Generated by Django 4.1.1 on 2022-11-02 06:20

import wagtail.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_alter_articlepage_options_alter_countrypage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsimage",
            name="file",
            field=models.ImageField(
                height_field="height",
                max_length=1024,
                upload_to=wagtail.images.models.AbstractImage.get_upload_to,
                verbose_name="file",
                width_field="width",
            ),
        ),
    ]
