# Generated by Django 4.1.3 on 2022-11-09 15:19

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("app", "0027_footersetting_headernavigationsetting_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navigation",
                    wagtail.fields.StreamField(
                        [
                            (
                                "internal_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                help_text="If set this replaces the page title",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "external_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("url", wagtail.blocks.URLBlock(required=True)),
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "button",
                    wagtail.fields.StreamField(
                        [
                            (
                                "internal_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(
                                                help_text="If set this replaces the page title",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "external_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("url", wagtail.blocks.URLBlock(required=True)),
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header",
            },
        ),
        migrations.AlterField(
            model_name="footersetting",
            name="description",
            field=models.CharField(
                blank=True,
                default="Humanitarian OpenStreetMap Team (HOT) sits at the nexus of participatory mapping, community-led development, humanitarian response, open data and tech.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="HeaderNavigationSetting",
        ),
    ]
