# Generated by Django 4.1.3 on 2022-11-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_activationprojectpage_content_and_more"),
        ("app", "0028_headersetting_alter_footersetting_description_and_more"),
    ]

    operations = []
