# Generated by Django 4.1.3 on 2022-11-23 12:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_alter_activationprojectpage_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openmappinghubindexpage",
            name="about_us_copy",
            field=wagtail.fields.RichTextField(blank=True, max_length=1500, null=True),
        ),
    ]
