# Generated by Django 4.1.3 on 2022-11-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_openmappinghubindexpage_about_us_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="openmappinghubindexpage",
            name="email",
            field=models.EmailField(default="comms@hotosm.org", max_length=254),
        ),
        migrations.AddField(
            model_name="openmappinghubindexpage",
            name="facebook",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="openmappinghubindexpage",
            name="mastodon",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="openmappinghubindexpage",
            name="twitter",
            field=models.URLField(default=""),
        ),
    ]
