# Generated by Django 4.1.3 on 2022-11-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_impactareapage_theme_class_and_more"),
        ("app", "0034_alter_activationprojectpage_content_and_more"),
    ]

    operations = []
