# Generated by Django 4.1.3 on 2022-11-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_openmappinghubindexpage_about_us"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openmappinghubindexpage",
            name="about_us_copy",
        ),
    ]
