# Generated by Django 4.1.3 on 2022-11-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_geography"),
        ("app", "0039_remove_openmappinghubindexpage_about_us_copy"),
    ]

    operations = []
