# Generated by Django 4.1.3 on 2022-11-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_add_team_carousel_block"),
        ("app", "0040_add_testimonials_block"),
    ]

    operations = []
