# Generated by Django 4.1.3 on 2022-11-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_alter_activationprojectpage_content_and_more"),
        ("app", "0042_alter_activationprojectpage_content_and_more"),
    ]

    operations = []
