# Generated by Django 4.1.3 on 2022-11-28 13:32

import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_merge_20221129_0913"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="related_impact_areas",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="app.impactareapage"
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="related_impact_areas",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="app.impactareapage"
            ),
        ),
        migrations.AddField(
            model_name="opportunitypage",
            name="related_impact_areas",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="app.impactareapage"
            ),
        ),
        migrations.AddField(
            model_name="organisationpage",
            name="related_impact_areas",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="app.impactareapage"
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="related_impact_areas",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="app.impactareapage"
            ),
        ),
    ]
