# Generated by Django 4.1.3 on 2022-11-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_add_resources_block"),
        ("app", "0044_add_related_impact_areas"),
    ]

    operations = []
