# Generated by Django 4.1.3 on 2022-11-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_alter_activationprojectpage_content_and_more"),
        ("app", "0045_merge_20221129_1513"),
    ]

    operations = []
