# Generated by Django 4.1.3 on 2022-11-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_alter_activationprojectpage_content_and_more"),
        ("app", "0046_merge_20221129_1519"),
    ]

    operations = []
