# Generated by Django 4.1.3 on 2022-11-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_add_open_mapping_hubs_block"),
        ("app", "0047_merge_20221129_1616"),
    ]

    operations = []
