# Generated by Django 4.1.3 on 2022-11-29 19:44

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import app.models.wagtail.pages


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_merge_20221130_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="theme_class",
            field=models.CharField(
                choices=[
                    ("theme-blue", "blue"),
                    ("theme-red", "red"),
                    ("theme-yellow", "yellow"),
                    ("theme-orange", "orange"),
                    ("theme-pink", "pink"),
                    ("theme-purple", "purple"),
                    ("theme-indigo", "indigo"),
                    ("theme-teal", "teal"),
                    ("theme-green", "green"),
                    ("theme-gray", "gray"),
                ],
                default="theme-blue",
                help_text="Pick the colour palette for this page's elements. Defaults to HOT blue.",
                max_length=50,
                verbose_name="Theme colour",
            ),
        ),
        migrations.AlterField(
            model_name="countrypage",
            name="isoa2",
            field=models.CharField(
                help_text="ISO Alpha 2 country code",
                max_length=2,
                validators=[app.models.wagtail.pages.validate_genuine_isoa2_code],
            ),
        ),
        migrations.AlterField(
            model_name="countrypage",
            name="isoa3",
            field=models.CharField(
                blank=True,
                help_text="ISO Alpha 3 country code",
                max_length=3,
                null=True,
                validators=[app.models.wagtail.pages.validate_genuine_isoa3_code],
            ),
        ),
    ]
