# Generated by Django 4.1.3 on 2022-12-01 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("app", "0049_add_tool_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolpage",
            name="guide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_guide",
                to="wagtailcore.page",
            ),
        ),
    ]
