# Generated by Django 4.1.3 on 2022-12-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_toolpage_guide"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolpage",
            name="tags",
        ),
    ]
