# Generated by Django 4.1.3 on 2022-12-01 13:08

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_personpage_email_personpage_linkedin_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personpage",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
