# Generated by Django 4.1.3 on 2022-12-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("app", "0051_remove_toolpage_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolpage",
            name="guide",
            field=models.ForeignKey(
                blank=True,
                help_text="Page that has a guide to the usage of this tool",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_guide",
                to="wagtailcore.page",
            ),
        ),
    ]
