# Generated by Django 4.1.3 on 2022-12-01 19:37

import django.db.models.deletion
import modelcluster.contrib.taggit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("app", "0052_alter_toolpage_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="app.TaggedOrganisation",
                to="app.HOTOSMTag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="toolpage",
            name="guide",
            field=models.ForeignKey(
                blank=True,
                help_text="Page that has a guide to the usage of this tool",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_guide",
                to="wagtailcore.page",
                verbose_name="Tool guide",
            ),
        ),
    ]
