# Generated by Django 4.1.3 on 2022-12-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_personpage_facebook_url_and_more"),
        ("app", "0055_alter_activationprojectpage_content_and_more"),
    ]

    operations = []
