# Generated by Django 4.1.3 on 2022-12-02 00:14

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_articlepage_added_authors_articlepage_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="added_authors",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Add authors who haven't manually edited the page through Wagtail",
                related_name="+",
                to="app.personpage",
            ),
        ),
        migrations.AlterField(
            model_name="topichomepage",
            name="added_authors",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Add authors who haven't manually edited the page through Wagtail",
                related_name="+",
                to="app.personpage",
            ),
        ),
        migrations.AlterField(
            model_name="topicpage",
            name="added_authors",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Add authors who haven't manually edited the page through Wagtail",
                related_name="+",
                to="app.personpage",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                help_text="Public profile page. Select from existing profiles, or create a new Person Page and come back here to select it.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user",
                to="app.personpage",
            ),
        ),
    ]
