# Generated by Django 4.1.3 on 2022-12-08 18:55

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_alter_authorship"),
    ]

    operations = [
        migrations.RenameField(
            model_name="landingpage",
            old_name="show_header",
            new_name="show_navbar",
        ),
        migrations.AddField(
            model_name="landingpage",
            name="show_title",
            field=models.BooleanField(default=True),
        ),
    ]
