# Generated by Django 4.1.3 on 2022-12-14 13:30

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_rename_show_header_landingpage_show_navbar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Public profile page. Select from existing profiles, or create a new Person Page and come back here to select it.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user",
                to="app.personpage",
            ),
        ),
    ]
