# Generated by Django 4.1.3 on 2023-04-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_alter_activationprojectpage_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Public profile page. Select from existing profiles, or create a new Person Page and come back here to select it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="app.personpage",
            ),
        ),
    ]
