name: Regular Server Restart
on:
  schedule:
    - cron: "0 3 * * *"
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    environment:
      name: staging
      url: https://alpha.hotosm.org
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly apps restart hotosm-staging
